# Generated by Django 3.1.7 on 2021-04-13 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.standardprice'),
        ),
        migrations.AlterField(
            model_name='academic',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.volumeprice'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='academic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.academic'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='retail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.retail'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.standardprice'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.volumeprice'),
        ),
        migrations.AlterField(
            model_name='standardprice',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standardprice',
            name='upgrade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volumeprice',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volumeprice',
            name='upgrade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
